ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLESPACE ventas_datos_ts
    DATAFILE 'C:\APP\USER\PRODUCT\21C\ORADATA\XE\XEPDB1\ventas_datos001.dbf'
    SIZE 50M
    AUTOEXTEND ON 
    NEXT 10M
    MAXSIZE 500M
    EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ventas_idx_ts
    DATAFILE 'C:\APP\USER\PRODUCT\21C\ORADATA\XE\XEPDB1\ventas_indices001.dbf'
    SIZE 30M
    AUTOEXTEND ON 
    NEXT 10M
    MAXSIZE 300M
    EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT AUTO;

SELECT tablespace_name, status
FROM dba_tablespaces
WHERE tablespace_name IN ('VENTAS_DATOS_TS', 'VENTAS_IDX_TS');



ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER usr_ventas IDENTIFIED BY ventas368
DEFAULT TABLESPACE ventas_datos_ts
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON ventas_datos_ts
QUOTA UNLIMITED ON ventas_idx_ts;
GRANT CREATE SESSION TO usr_ventas;
GRANT CREATE TABLE TO usr_ventas;
GRANT CREATE VIEW TO usr_ventas;
GRANT CREATE SEQUENCE TO usr_ventas;
GRANT CREATE TRIGGER TO usr_ventas;




SELECT tablespace_name, file_name, bytes/1024/1024 AS tamanio_mb, autoextensible
FROM dba_data_files
WHERE tablespace_name IN ('VENTAS_DATOS_TS', 'VENTAS_IDX_TS');