CREATE TABLE proveedor (
    codigo_proveedor VARCHAR2(10) NOT NULL,
    razon_social VARCHAR2(150) NOT NULL,
    ruc VARCHAR2(20) NOT NULL,
    direccion VARCHAR2(200),
    telefono VARCHAR2(30),
    celular VARCHAR2(30),
    email VARCHAR2(100),
    estado CHAR(1) DEFAULT 'A' NOT NULL,

    CONSTRAINT pk_proveedor 
    PRIMARY KEY (codigo_proveedor)
    USING INDEX TABLESPACE ventas_idx_ts,

    CONSTRAINT uk_proveedor_ruc 
    UNIQUE (ruc)
    USING INDEX TABLESPACE ventas_idx_ts,

    CONSTRAINT chk_proveedor_estado 
    CHECK (estado IN ('A', 'I'))
)
TABLESPACE ventas_datos_ts;


CREATE TABLE cliente (
    codigo_cliente VARCHAR2(10) NOT NULL,
    razon_social VARCHAR2(150) NOT NULL,
    cedula_ruc VARCHAR2(20) NOT NULL,
    nombre_comercial VARCHAR2(150),
    direccion VARCHAR2(200),
    telefono VARCHAR2(30),
    celular VARCHAR2(30),
    email VARCHAR2(100),
    estado CHAR(1) DEFAULT 'A' NOT NULL,

    CONSTRAINT pk_cliente 
    PRIMARY KEY (codigo_cliente)
    USING INDEX TABLESPACE ventas_idx_ts,

    CONSTRAINT uk_cliente_cedula_ruc 
    UNIQUE (cedula_ruc)
    USING INDEX TABLESPACE ventas_idx_ts,

    CONSTRAINT chk_cliente_estado 
    CHECK (estado IN ('A', 'I'))
)
TABLESPACE ventas_datos_ts;

CREATE TABLE item (
    codigo_item VARCHAR2(20) NOT NULL,
    codigo_alterno VARCHAR2(20),
    descripcion VARCHAR2(300) NOT NULL,
    unidad_medida VARCHAR2(20),
    stock NUMBER(18,4) DEFAULT 0 NOT NULL,
    precio_costo NUMBER(18,6) DEFAULT 0 NOT NULL,
    precio_venta NUMBER(18,6) DEFAULT 0 NOT NULL,
    estado CHAR(1) DEFAULT 'A' NOT NULL,
    codigo_proveedor VARCHAR2(10) NOT NULL,

    CONSTRAINT pk_item
    PRIMARY KEY (codigo_item)
    USING INDEX TABLESPACE ventas_idx_ts,

    CONSTRAINT fk_item_proveedor
    FOREIGN KEY (codigo_proveedor)
    REFERENCES proveedor(codigo_proveedor),

    CONSTRAINT chk_item_estado
    CHECK (estado IN ('A', 'I')),

    CONSTRAINT chk_item_stock
    CHECK (stock >= 0),

    CONSTRAINT chk_item_precio_costo
    CHECK (precio_costo >= 0),

    CONSTRAINT chk_item_precio_venta
    CHECK (precio_venta >= 0)
)
TABLESPACE ventas_datos_ts;


CREATE TABLE codigo_barra (
    codigo_barra VARCHAR2(50) NOT NULL,
    codigo_item VARCHAR2(20) NOT NULL,
    estado CHAR(1) DEFAULT 'A' NOT NULL,

    CONSTRAINT pk_codigo_barra
    PRIMARY KEY (codigo_barra)
    USING INDEX TABLESPACE ventas_idx_ts,

    CONSTRAINT fk_codigo_barra_item
    FOREIGN KEY (codigo_item)
    REFERENCES item(codigo_item),

    CONSTRAINT chk_codigo_barra_estado
    CHECK (estado IN ('A', 'I'))
)
TABLESPACE ventas_datos_ts;

CREATE TABLE venta (
    id_venta NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    tipo_documento VARCHAR2(10) NOT NULL,
    serie VARCHAR2(20),
    numero_documento VARCHAR2(30) NOT NULL,
    fecha_emision DATE DEFAULT SYSDATE NOT NULL,
    subtotal NUMBER(18,4) DEFAULT 0 NOT NULL,
    descuento NUMBER(18,4) DEFAULT 0 NOT NULL,
    iva_valor NUMBER(18,4) DEFAULT 0 NOT NULL,
    total NUMBER(18,4) DEFAULT 0 NOT NULL,
    codigo_cliente VARCHAR2(10) NOT NULL,

    CONSTRAINT pk_venta
    PRIMARY KEY (id_venta)
    USING INDEX TABLESPACE ventas_idx_ts,

    CONSTRAINT fk_venta_cliente
    FOREIGN KEY (codigo_cliente)
    REFERENCES cliente(codigo_cliente),

    CONSTRAINT uk_venta_documento
    UNIQUE (tipo_documento, serie, numero_documento)
    USING INDEX TABLESPACE ventas_idx_ts,

    CONSTRAINT chk_venta_subtotal
    CHECK (subtotal >= 0),

    CONSTRAINT chk_venta_descuento
    CHECK (descuento >= 0),

    CONSTRAINT chk_venta_iva
    CHECK (iva_valor >= 0),

    CONSTRAINT chk_venta_total
    CHECK (total >= 0)
)
TABLESPACE ventas_datos_ts;


CREATE TABLE detalle_venta (
    id_detalle NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    id_venta NUMBER(19) NOT NULL,
    codigo_item VARCHAR2(20) NOT NULL,
    cantidad NUMBER(18,4) NOT NULL,
    precio_unitario NUMBER(18,6) NOT NULL,
    subtotal NUMBER(18,4) NOT NULL,
    total_linea NUMBER(18,4) NOT NULL,

    CONSTRAINT pk_detalle_venta
    PRIMARY KEY (id_detalle)
    USING INDEX TABLESPACE ventas_idx_ts,

    CONSTRAINT fk_detalle_venta_venta
    FOREIGN KEY (id_venta)
    REFERENCES venta(id_venta),

    CONSTRAINT fk_detalle_venta_item
    FOREIGN KEY (codigo_item)
    REFERENCES item(codigo_item),

    CONSTRAINT chk_detalle_cantidad
    CHECK (cantidad > 0),

    CONSTRAINT chk_detalle_precio
    CHECK (precio_unitario >= 0),

    CONSTRAINT chk_detalle_subtotal
    CHECK (subtotal >= 0),

    CONSTRAINT chk_detalle_total_linea
    CHECK (total_linea >= 0)
)
TABLESPACE ventas_datos_ts;





SELECT table_name, tablespace_name
FROM user_tables
ORDER BY table_name;

SELECT constraint_name, table_name, constraint_type, status
FROM user_constraints
ORDER BY table_name, constraint_name;